src/Salud/Controllers/VendedoresController.cs
using Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogicaNegocio;
using System.EnterpriseServices;


namespace WebPlanesCS.Controllers
{
    public class VendedoresController : Controller
    {
        private LNVendedores LNVendedores = new LNVendedores();
        private LNSociedades LNSociedades = new LNSociedades();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetLista()
        {
            var lstVendedores = LNVendedores.ObtenerTodos();
            return Json(new { data = lstVendedores.ToList() }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult AddOrEdit(string id =null)
        {
            if (id is null)
            {
                ViewBag.IdSociedad = new SelectList(LNSociedades.ObtenerTodos().ToList(), "IdSociedad", "RazonSocial");
                var ENVendedores = new ENVendedores();
                return View(ENVendedores);
            }
            else
            {
                ENVendedores mVendedorEditar = LNVendedores.ObtenerTodos().Find(smodel => smodel.CodigoVendedor == id);
                ViewBag.IdSociedad = new SelectList(LNSociedades.ObtenerTodos().ToList(), "IdSociedad", "RazonSocial", mVendedorEditar.IdSociedad);
                return View(mVendedorEditar);
            }
        }

        public ActionResult AddOrEdit(ENVendedores pla)
        {
            if (pla.CodigoVendedor is  null)
            {
                if (LNVendedores.Insertar(pla))
                {
                    ViewBag.Message = "Registro Grabado Correctamente";
                    ModelState.Clear();
                }
                return Json(new { success = true, message = "Grabado Correctamente" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                if (LNVendedores.Actualizar(pla))
                {
                    ViewBag.Message = "Registro Grabado Correctamente";
                    ModelState.Clear();
                }
                return Json(new { success = true, message = "Actualizado Correctamente" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                if (LNVendedores.Eliminar(id))
                {
                    return Json(new { success = true, message = "Eliminado Correctamente" }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { success = true, message = "Eliminado Correctamente" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return View();
            }
        }


    }
}

src/Salud/Views/Vendedores/AddOrEdit.cshtml
@model Entidades.ENVendedores

@{
    Layout = null;
}
@*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.js"></script>*@
@using (Html.BeginForm("AddOrEdit", "Vendedores", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CodigoVendedor)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                @Html.LabelFor(model => model.IdSociedad, "Sociedad", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("IdSociedad", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdSociedad)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ApellidoPaterno, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.ApellidoPaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ApellidoMaterno, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.ApellidoMaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })

            </div>

        </div>
        <div class="col-sm-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
            @Html.LabelFor(model => model.CodigoUsuario, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.CodigoUsuario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CodigoUsuario, "", new { @class = "text-danger" })
        </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CodigoPerfil, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.CodigoPerfil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoPerfil, "", new { @class = "text-danger" })
            </div>
            @*<div class="form-group">
            @Html.LabelFor(model => model.IdPersona, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.IdPersona, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdPersona, "", new { @class = "text-danger" })
        </div>*@
            @*<div class="form-group">
            @Html.LabelFor(model => model.IdSociedad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdSociedad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdSociedad, "", new { @class = "text-danger" })
            </div>
        </div>*@

            @*<div class="form-group">
            @Html.LabelFor(model => model.IdPersonaSociedad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersonaSociedad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersonaSociedad, "", new { @class = "text-danger" })
            </div>
        </div>*@
            @*<div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })

        </div>*@

        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Grabar" id="btnSubmit" class="btn btn-primary" />
        <input type="reset" value="Limpiar" class="btn" />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
}

src/Salud/Views/Vendedores/Index.cshtml
@{
    ViewBag.Title = "VistaVendedores";
}

<h2>Lista Vendedores</h2>


<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Vendedores")')"><i class="fa fa-plus"></i> Agregar</a>
<table id="TablaLista" class="display table-bordered">
    <thead>
        <tr style="background-color:#3d566e; color:#ecf0f1">
            <th>ApellidoPaterno</th>
            <th>ApellidoMaterno</th>
            <th>Nombres</th>
            <th>Direccion</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>Sociedad</th>
            <th></th>
        </tr>
    </thead>
</table>

<!-- Normal -->
<link href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/scroller/2.0.2/css/scroller.dataTables.min.css"></script>

    <script>
    var Popup, dataTable;
    $(document).ready(function () {

        dataTable = $("#TablaLista").DataTable
            ({
                "ajax": {
                    "url": "/Vendedores/GetLista",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "ApellidoPaterno" },
                    { "data": "ApellidoMaterno" },
                    { "data": "Nombres" },
                    { "data": "Direccion" },
                    { "data": "Telefono" },
                    { "data": "Email" },
                    { "data": "RazonSocial" },
                    { "data": "CodigoVendedor" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","Vendedores")/" + data + "')><i class='fa fa-pencil'></i> </a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> </a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }
                ],
                "language":
                {
                    "emptyTable": "Sin datos  en la tabla.",
                    "info": "Del _START_ al _END_ de _TOTAL_ ",
                    "infoEmpty": "Mostrando 0 registros de un total de 0.",
                    "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                    "infoPostFix": "",
                    "lengthMenu": "Mostrar _MENU_ registros",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "searchPlaceholder": "",
                    "zeroRecords": "No se han encontrado coincidencias.",
                    "paginate": {
                        "first": "<<",
                        "last": ">>",
                        "next": ">",
                        "previous": "<"
                    },
                    "aria": {
                        "sortAscending": "Ordenación ascendente",
                        "sortDescending": "Ordenación descendente"
                    }
                },
                "lengthMenu": [[5, 10, 50, -1], [5, 10, 50, "Todos"]]
            }
        );

        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    title: 'Datos del Vendedor',
                    height: 500,
                    width: 700,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }

                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if($(form).valid()){
                $.ajax({
                    type : "POST",
                    url : form.action,
                    data : $(form).serialize(),
                    success : function (data) {
                        if(data.success)
                        {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message,{
                                globalPosition :"top center",
                                className : "success"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {

            @*Swal.fire({
                title: '¿Desea eliminar el registro?',
                text: "Se eliminará el vendedor.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, continuar',
                cancelButtonText: 'No'
            }).then(function (result) {
                if (result.value == true) {

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete","Vendedores")/' + id,
                        success: function (data) {
                            if (data.success)
                            {
                                dataTable.ajax.reload();
                                $.notify(data.message, {
                                    globalPosition: "top center",
                                    className: "success"
                                })

                            }
                        }

                    });

                }
            });*@



            if(confirm('Desea Eliminar el Registro?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Vendedores")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }

    </script>
}