src/Salud/Controllers/CanalController.cs
using Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogicaNegocio;
using Utilitarios;
using Salud.App_Start;

namespace Salud.Controllers
{
    public class CanalController : Controller
    {
        private LNCanales LNCanales = new LNCanales();
        private LNSociedades LNSociedades = new LNSociedades();
        public ActionResult Index(int page = 0)
        {

            var contador = LNCanal.Cantidad(Session["SociedadUsuario"].ToString());
            ViewData["todos"] = contador;
            ViewData["ultimo"] = contador / 100;

            if (page != 0)
            {
                if (page < (contador / 100))
                {
                    ViewData["pageCount"] = page;
                }
                else
                {
                    ViewData["pageCount"] = contador / 100;
                }
            }

            if (ViewData["pageCount"] == null && page == 0)
            {
                ViewData["pageCount"] = 1;
                page = 1;
            }


            if (TempData["Seleccion"] != null)
            {
                ViewData["Seleccion"] = TempData["Seleccion"];
            }
            else
            {
                ViewData["Seleccion"] = Session["SociedadUsuario"];
            }

            if (TempData["mensaje"] != null)
            {
                TempData["mensaje"] = TempData["mensaje"];
            }

            var lstSociedades = LNSociedades.ObtenerTodos();
            var lstSociedades_ = new SelectList(lstSociedades.ToList(), "IdSociedad", "RazonSocial", ViewData["Seleccion"]);
            ViewData["ListaSociedades"] = lstSociedades_;

            var lstTiposComision = LNTipoComision.ObtenerTodos();
            var lstTiposComision_ = new SelectList(lstTiposComision.ToList(), "IdTipoComision", "DescripcionTipoComision");
            ViewData["ListaTipoComision"] = lstTiposComision_;

            if (TempData["Canales"] != null)
            {
                ViewData["Canales"] = TempData["Canales"];
            }
            else
            {
                if (Session["SociedadUsuario"] != null)
                {
                    var sociedadSesion = Session["SociedadUsuario"];
                    var lstCanales = LNCanal.ObtenerTodos(page,100,"","",sociedadSesion.ToString());
                    ViewData["Canales"] = lstCanales;
                }
                else
                {
                    var lstCanales = LNCanal.ObtenerTodos(page, 100, "", "","0");
                    ViewData["Canales"] = lstCanales;
                }
                
            }

            return View();
        }

        [SessionExpire]
        [HttpPost]
        public ActionResult Index(int page = 0,string txtBusquedaCanal = "", string mensaje = "")
        {

            var contador = LNCanal.Cantidad(Session["SociedadUsuario"].ToString());
            ViewData["todos"] = contador;
            ViewData["ultimo"] = contador / 100;

            if (page != 0)
            {
                if (page < (contador / 100))
                {
                    ViewData["pageCount"] = page;
                }
                else
                {
                    ViewData["pageCount"] = contador / 100;
                }
            }

            if (ViewData["pageCount"] == null && page == 0)
            {
                ViewData["pageCount"] = 1;
                page = 1;
            }

            var lstSociedades = LNSociedades.ObtenerTodos();
            var lstSociedades_ = new SelectList(lstSociedades.ToList(), "IdSociedad", "RazonSocial", Session["SociedadUsuario"].ToString());
            ViewData["ListaSociedades"] = lstSociedades_;

            var lstTiposComision = LNTipoComision.ObtenerTodos();
            var lstTiposComision_ = new SelectList(lstTiposComision.ToList(), "IdTipoComision", "DescripcionTipoComision", Session["SociedadUsuario"].ToString());
            ViewData["ListaTipoComision"] = lstTiposComision_;

            if (Session["SociedadUsuario"] != null)
            {
                var sociedadSesion = Session["SociedadUsuario"];
                var lstCanales = LNCanal.ObtenerTodos(1, 100, "", txtBusquedaCanal, sociedadSesion.ToString());
                ViewData["Canales"] = lstCanales;
                //TempData["Vendedores"] = lstVendedores;
            }
            else
            {
                var lstCanales = LNCanal.ObtenerTodos(1, 100, "", txtBusquedaCanal, "0");
                ViewData["Canales"] = lstCanales;
                //TempData["Vendedores"] = lstVendedores;
            }

            TempData["Seleccion"] = Session["SociedadUsuario"];
            TempData["mensaje"] = mensaje;
            return View();
        }

        //[HttpGet]
        //public ActionResult GetLista(string slcSociedad, string mensaje)
        //{
        //    var lstCanales = LNCanal.ObtenerTodos(slcSociedad);
        //    TempData["Canales"] = lstCanales;
        //    TempData["Seleccion"] = slcSociedad;
        //    TempData["mensaje"] = mensaje;
        //    return RedirectToAction("Index");
        //}

        [HttpGet]
        public JsonResult GetListaJSON(string slcSociedad)
        {
            var lstCanales = LNCanal.ObtenerTodos(slcSociedad);
            TempData["CanalesJSON"] = new SelectList(lstCanales.ToList(), "IDCanal", "DescripcionCanal");
            return Json(TempData["CanalesJSON"], JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Mantenimiento(ENCanales canal)
        {
            var valor = 0;
            if (canal.IDCanal > 0)
            {
                if (LNCanal.Actualizar(canal))
                {
                    valor = canal.IdSociedad;
                    ModelState.Clear();
                }
                return RedirectToAction("Index", new { mensaje = "Canal modificado" });
            }
            else
            {
                if (LNCanal.Insertar(canal))
                {
                    valor = canal.IdSociedad;
                    ModelState.Clear();
                }
                return RedirectToAction("Index", new { mensaje = "Canal registrado" });

            }
        }

        [HttpGet]
        public ActionResult MantenimientoComision(ENCanales vcomision,string slcSociedad)
        {
            var valor = ""; 
            if (LNCanal.InsertarComision(vcomision))
            {
                valor = Session["SociedadUsuario"].ToString();
                ModelState.Clear();
            }
            return RedirectToAction("Index", new { mensaje = "Comisión Asignada" });
        }

        [SessionExpire]
        [HttpPost]
        public ActionResult Eliminar(int Id)
        {
            try
            {
                if (LNCanal.Eliminar(Id))
                {
                    var mensaje = "Excelente, Canal eliminado.";
                    return Json(mensaje, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var mensaje = "Error";
                    return Json(mensaje, JsonRequestBehavior.AllowGet);
                }
                
            }
            catch (Exception ex)
            {
                var mensaje = "Error, El Canal asignado tiene comisiones vigentes.";
                return Json(mensaje, JsonRequestBehavior.AllowGet);
            }           
            
        }


    }
}

src/Salud/Controllers/ClientesController.cs
using Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogicaNegocio;
using Utilitarios;
using Salud.App_Start;
using Salud.ViewModels;

namespace Salud.Controllers
{
    public class ClientesController : Controller
    {
        private LNUbigeoDpto LNUbigeoDpto = new LNUbigeoDpto();
        private LNUbigeoProv LNUbigeoProv = new LNUbigeoProv();
        private LNUbigeoDist LNUbigeoDist = new LNUbigeoDist();

        // GET: Clientes
        [SessionExpire]
        public ActionResult Index(int page = 0)
        {
            var contador = LNClientes.Cantidad();
            ViewData["todos"] = contador;
            ViewData["ultimo"] = contador / 100;

            if (page != 0)
            {
                if (page < (contador / 100))
                {
                    ViewData["pageCount"] = page;
                }
                else
                {
                    ViewData["pageCount"] = contador / 100;
                }
            }

            if (ViewData["pageCount"]  == null && page == 0)
            {
                ViewData["pageCount"] = 1;
                page = 1;
            }



            ViewBag.CodigoTipoCliente = new SelectList(LNTipoCliente.ObtenerTodos().ToList(), "CodigoTipoCliente", "DescripcionTipoCliente");
            ViewBag.Clientes = LNClientes.ObtenerTodos(page,100,"","");
            ViewBag.IdNombreTabla = "01";
            //var VMCliente = new List<ENClientes>();int page, int rows, string type, string Keywords
            //var VMUbigeo = new List<ENUbigeoCompleto>();
            var VMCliente = new ENClientes();
            var VMUbigeo = new ENUbigeoCompleto();

            var ClienteViewModel = new VMClientes
            {
                Clientes = VMCliente,
                Ubigeo = VMUbigeo
            };

            if (TempData["Mensaje_Cliente"] != null)
            {
                ViewBag.Message = TempData["Mensaje_Cliente"];
            }

            //return View(ClienteViewModel);

            return View();
        }


        // GET: Clientes
        [SessionExpire]
        [HttpPost]
        public ActionResult Index(int page = 0,string hdCodigoTipoCliente = "", string txtBusquedaClientes = "")
        {

            var contador = LNClientes.Cantidad();
            ViewData["todos"] = contador;
            ViewData["ultimo"] = contador / 100;

            if (page != 0)
            {
                if (page < (contador / 100))
                {
                    ViewData["pageCount"] = page;
                }
                else
                {
                    ViewData["pageCount"] = contador / 100;
                }
            }

            if (ViewData["pageCount"] == null && page == 0)
            {
                ViewData["pageCount"] = 1;
                page = 1;
            }

           

            ViewBag.CodigoTipoCliente = new SelectList(LNTipoCliente.ObtenerTodos().ToList(), "CodigoTipoCliente", "DescripcionTipoCliente");
            ViewBag.Clientes = LNClientes.ObtenerTodos(1, 100, hdCodigoTipoCliente, txtBusquedaClientes);
            ViewBag.IdNombreTabla = hdCodigoTipoCliente.ToString();
            //var VMCliente = new List<ENClientes>();int page, int rows, string type, string Keywords
            //var VMUbigeo = new List<ENUbigeoCompleto>();
            var VMCliente = new ENClientes();
            var VMUbigeo = new ENUbigeoCompleto();

            var ClienteViewModel = new VMClientes
            {
                Clientes = VMCliente,
                Ubigeo = VMUbigeo
            };

            if (TempData["Mensaje_Cliente"] != null)
            {
                ViewBag.Message = "Cliente registrado correctamente";
            }

            //return View(ClienteViewModel);

            return View("Index");
        }


        public ActionResult Test()
        {
            return View();
        }

        public ActionResult _Prueba()
        {
            return View();
        }


        public ActionResult Buscar()

        {
            ViewBag.Clientes = LNClientes.ObtenerTodos();
            return PartialView("_BusquedaClientes", LNClientes.ObtenerTodos());
        }

        [HttpGet]
        public ActionResult Crear(string id = "")
        {
            var VMCliente = new ENClientes();
            var VMUbigeo = new ENUbigeoCompleto();

            if (TempData["Tarjeta_Add"] != null)
            {
                ViewBag.TarjetaAdd = TempData["Tarjeta_Add"];
            }

            if (TempData["Tarjeta_Update"] != null)
            {
                ViewBag.TarjetaUpdate = TempData["Tarjeta_Update"];
            }

            if (TempData["Tarjeta_Remove"] != null)
            {
                ViewBag.TarjetaRemove = TempData["Tarjeta_Remove"];
            }


            if (id != "")
            {
                VMCliente = LNClientes.ObtenerUno(id);
                ViewBag.CodigoDpto = new SelectList(LNUbigeoDpto.ObtenerDpto().ToList(), "CodigoDpto", "DescripcionDpto", VMCliente.CodigoDpto);
                ViewBag.CodigoProv = new SelectList(LNUbigeoProv.ObtenerProv(VMCliente.CodigoDpto).ToList(), "CodigoProv", "DescripcionProv", VMCliente.CodigoProv);
                ViewBag.CodigoDist = new SelectList(LNUbigeoDist.ObtenerDist(VMCliente.CodigoDpto, VMCliente.CodigoProv).ToList(), "CodigoDist", "DescripcionDist", VMCliente.CodigoDist);
                ViewBag.CodigoCorredor = new SelectList(LNSCTRCorredor.ObtenerTodos().ToList(), "CodigoCorredor", "DescripcionCorredor", VMCliente.CodigoCorredor);
                ViewBag.CodigoEjecutivo = new SelectList(LNSCTREjecutivos.ObtenerTodos().ToList(), "CodigoEjecutivo", "NombreEjecutivo", VMCliente.CodigoEjecutivo);
                ViewBag.CodigoTipoCliente = new SelectList(LNTipoCliente.ObtenerTodos().ToList(), "CodigoTipoCliente", "DescripcionTipoCliente", VMCliente.CodigoTipoCliente);
                ViewBag.CodigoDocumentoIdentidad = new SelectList(LNTipoDocumentoIdentidad.ObtenerTodos().ToList(), "CodigoDocumentoIdentidad", "DescripcionDocumentoIdentidad", VMCliente.CodigoDocumentoIdentidad);
                ViewBag.Tarjetas = LNClientes.ObtenerTarjetas(id).OrderByDescending(x => x.IdClienteTarjetas).ToList();
                ViewBag.MarcaTarjetas = new SelectList(LNMarcaTarjeta.ObtenerTodos().ToList(), "CodigoMarcaTarjeta", "DescripcionMarcaTarjeta");
                ViewBag.CodigoClienteID = id;
                //ViewBag.CodigoVendedor = new SelectList(LNTipoDocumentoIdentidad.ObtenerTodos().ToList(), "CodigoDocumentoIdentidad", "DescripcionDocumentoIdentidad");

            }
            else
            {
                ViewBag.CodigoDpto = new SelectList(LNUbigeoDpto.ObtenerDpto().ToList(), "CodigoDpto", "DescripcionDpto");
                ViewBag.CodigoProv = new SelectList(LNUbigeoProv.ObtenerProv("15").ToList(), "CodigoProv", "DescripcionProv");
                ViewBag.CodigoDist = new SelectList(LNUbigeoDist.ObtenerDist("15", "01").ToList(), "CodigoDist", "DescripcionDist");
                ViewBag.CodigoCorredor = new SelectList(LNSCTRCorredor.ObtenerTodos().ToList(), "CodigoCorredor", "DescripcionCorredor");
                ViewBag.CodigoEjecutivo = new SelectList(LNSCTREjecutivos.ObtenerTodos().ToList(), "CodigoEjecutivo", "NombreEjecutivo");
                ViewBag.CodigoTipoCliente = new SelectList(LNTipoCliente.ObtenerTodos().ToList(), "CodigoTipoCliente", "DescripcionTipoCliente");
                ViewBag.CodigoDocumentoIdentidad = new SelectList(LNTipoDocumentoIdentidad.ObtenerTodos().ToList(), "CodigoDocumentoIdentidad", "DescripcionDocumentoIdentidad");
                ViewBag.MarcaTarjetas = new SelectList(LNMarcaTarjeta.ObtenerTodos().ToList(), "CodigoMarcaTarjeta", "DescripcionMarcaTarjeta");
                ViewBag.CodigoClienteID = null;
                //ViewBag.CodigoVendedor = new SelectList(LNVendedor.ObtenerTodos("0").ToList(), "CodigoVendedor", "Nombres");
            }

            var ClienteViewModel = new VMClientes
            {
                Clientes = VMCliente,
                Ubigeo = VMUbigeo
            };


            return View(ClienteViewModel);

        }

        [SessionExpire]
        [HttpPost]
        public ActionResult Crear(VMClientes obj)
        {
            if (obj.Clientes.CodigoCliente is null)
            {

                if (LNClientes.Insertar(obj.Clientes))
                {
                    ViewBag.Message = "Registro Grabado Correctamente";
                    ModelState.Clear();
                    TempData["Mensaje_Cliente"] = "Cliente registrado correctamente";
                }
                //return Json(new { success = true, message = "Grabado Correctamente" }, JsonRequestBehavior.AllowGet);

            }
            else
            {

                if (LNClientes.Actualizar(obj.Clientes))
                {
                    ViewBag.Message = "Registro Actualizado Correctamente";
                    TempData["Mensaje_Cliente"] = "Registro Actualizado Correctamente";
                    ModelState.Clear();
                }
                //return Json(new { success = true, message = "Actualizado Correctamente" }, JsonRequestBehavior.AllowGet);

            }
            return RedirectToAction("Index", "Clientes");
        }

        [SessionExpire]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Eliminar(string id = "")
        {
            try
            {
                if (LNClientes.Eliminar(id))
                {
                    var mensaje = "Excelente, contratante eliminado.";
                    return Json(mensaje, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var mensaje = "Error, el contratante tiene contratos vigentes.";
                    return Json(mensaje, JsonRequestBehavior.AllowGet);
                }
            }

src/Salud/Views/Clientes/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>

src/Salud/Views/Clientes/_BusquedaClientes.cshtml
@using Entidades;
@section Styles {
    @Styles.Render("~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")
    @Styles.Render("~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css")
}

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Búsqueda de Clientes</h4>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table id="dglista" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Codigo</th>
                                    <th>RUC</th>
                                    <th>Razón Social</th>
                                    <th style="width: 15%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (ENClientes Clientes in (List<ENClientes>)ViewBag.Clientes)
                                {
                                    <tr>
                                        <td>@Clientes.CodigoCliente </td>
                                        <td>@Clientes.RucDni </td>
                                        <td>@Clientes.RazonSocial </td>
                                        <td class="project-actions text-center">
                                            <button name="BotonSeleccionar" id="Seleccionar" value="Seleccionar" class="btn btn-primary">Cotizar</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnEliminar" data-eliminar="">Eliminar</button>
                </div>
            </div>
        </div>
    </div>

@section Scripts {
    @Scripts.Render("~/Content/plugins/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Content/plugins/datatables-responsive/js/dataTables.responsive.min.js")
    @Scripts.Render("~/Content//plugins/datatables-responsive/js/responsive.bootstrap4.min.js")

    <script>
        $(function () {

            $('#dglista').DataTable({
                "paging": true,
                "lengthChange": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": false,
                "lengthMenu": [[5, 10, 50, -1], [5, 10, 50, "Todos"]],
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json"
                }
            });
        });
    </script>
}

src/Salud/Views/Clientes/_Prueba.cshtml
@using Entidades;
@{ ViewBag.Title = "Prueba";
    Layout = "~/Views/Shared/_Layout.cshtml"; }
@section Styles {
    @Styles.Render("~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")
    @Styles.Render("~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css")
}

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Canal")')"><i class="fa fa-plus"></i> Buscar</a>

<div class="card-body ">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" id="btnSeleccionar" data-eliminar="">Buscar</button>
</div>

<div id="showmodal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                @{
                Html.RenderPartial ("_BusquedaClientes");
                }
            </div> <! - /.modal-content ->
        </div> <! - /.modal-dialog ->
    </div> <! - /.modal ->
    <button id='open' data-toggle="modal" data-target="#showmodal"> modal abierto </button>
@section Scripts {

    @Scripts.Render("~/Content/plugins/jquery-validation/jquery.validate.min.js")
    @Scripts.Render("~/Content/plugins/jquery-validation/additional-methods.min.js")

    <script type="text/javascript">
        var Popup, dataTable;
        $(function () {
            $("#btnSeleccionar").click(function () {
                alert("Handler for .click() Cotizar called.");

                $.ajax({
                    type: "POST",
                    url: "/Clientes/Buscar",
                    contentType: "application/json; charset=utf-8",
                    dataType: "html",
                    success: function (response) {
                        alert("Success");
                        $('#resultado').html(response);
                        $('#resultado').modal('show');
                        $('#myModal').modal('show');
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            });
        });



        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);
                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Buscar Cliente',
                        height: 500,
                        width: 700,
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }

                    });
                });
        }
    </script>



}

src/Salud/Views/Clientes/_Ubigeo.cshtml
@model Entidades.ENUbigeoCompleto
<div>
    <div class="col-sm-2">
        <div class="form-group">
            @Html.LabelFor(model => model.CodigoDpto, "Departamento", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("CodigoDpto", null, new { id = "drpDepartamento", @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(model => model.CodigoDpto)
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            @Html.LabelFor(model => model.CodigoProv, "Provincia", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("CodigoProv", null, new { id = "drpProvincia", @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(model => model.CodigoProv)
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            @Html.LabelFor(model => model.CodigoDist, "Distrito", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("CodigoDist", null, new { id = "drpDistrito", @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(model => model.CodigoDist)
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#drpDepartamento').change(function () {
                $.ajax({
                    type: "post",
                    url: "/SCTRCotizacion/GetProvincia",
                    data: { dptoid: $('#drpDepartamento').val() },
                    datatype: "json",
                    traditional: true,
                    success: function (data) {
                        var provincia = "<select id='CodigoProv'>";
                        provincia = provincia + '<option value="">--Seleccionar--</option>';
                        for (var i = 0; i < data.length; i++) {
                            provincia = provincia + '<option value=' + data[i].CodigoProv + '>' + data[i].DescripcionProv + '</option>';
                        }
                        provincia = provincia + '</select>';
                        $('#drpProvincia').html(provincia);
                    }
                });
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#drpProvincia').change(function () {
                $.ajax({
                    type: "post",
                    url: "/SCTRCotizacion/GetDistrito",
                    data: { dptoid: $('#drpDepartamento').val(), provid: $('#drpProvincia').val() },
                    datatype: "json",
                    traditional: true,
                    success: function (data) {
                        var district = "<select id='CodigoDist'>";
                        district = district + '<option value="">--Seleccionar--</option>';
                        for (var i = 0; i < data.length; i++) {
                            district = district + '<option value=' + data[i].CodigoDist + '>' + data[i].DescripcionDist + '</option>';
                        }
                        district = district + '</select>';
                        $('#drpDistrito').html(district);
                    }
                });
            });
        });
    </script>




}